spring.application.name=studentmanagement

# db url
spring.datasource.url=jdbc:h2:mem:studentdb

#db driver
spring.datasource.driverClassName=org.h2.Driver

#db username
spring.datasource.username=sa

#db password
spring.datasource.password=

#hibernate auto created and updates
spring.jpa.hibernate.ddl-auto=update

#prints sql queries in console
spring.jpa.show-sql=true

#formats sql queries to make them readable
spring.jpa.properties.hibernate.format_sql=true

#enables h2 web console
spring.h2.console.enabled=true

#url to access h2 console
spring.h2.console.path=/h2-console
